#!/usr/bin/env python3
"""
MultiAgentAI21 Setup Script
This script helps you configure your environment variables and test your setup.
"""

import json
import os
from pathlib import Path


def create_env_file():
    """Create .env file with user input"""
    print("🔧 MultiAgentAI21 Environment Setup")
    print("=" * 40)

    # Get current directory
    current_dir = Path.cwd()
    env_file = current_dir / ".env"

    print(f"Creating .env file at: {env_file}")

    # Get Gemini API key
    print("\n1. Gemini API Key:")
    print("   Visit: https://makersuite.google.com/app/apikey")
    gemini_key = input("   Enter your Gemini API key: ").strip()

    if not gemini_key:
        print("❌ Gemini API key is required!")
        return False

    # Get Google Cloud credentials path
    print("\n2. Google Cloud Credentials:")

    # Look for the key file in current directory
    key_files = list(current_dir.glob("*key*.json"))
    if key_files:
        print(f"   Found credential file: {key_files[0]}")
        use_found = input("   Use this file? (y/n): ").strip().lower()

        if use_found == "y":
            credentials_path = str(key_files[0].absolute())
        else:
            credentials_path = input(
                "   Enter full path to your credentials JSON file: "
            ).strip()
    else:
        credentials_path = input(
            "   Enter full path to your credentials JSON file: "
        ).strip()

    if not credentials_path or not Path(credentials_path).exists():
        print(f"❌ Credentials file not found: {credentials_path}")
        return False

    # Create .env content
    env_content = f"""# MultiAgentAI21 Environment Configuration
# Generated by setup.py

# Google Cloud Configuration
GOOGLE_APPLICATION_CREDENTIALS={credentials_path}

# Gemini AI Configuration  
GEMINI_API_KEY={gemini_key}

# Project Configuration
PROJECT_ID=multiagentai21

# Optional: BigQuery Dataset
DEFAULT_DATASET=your_dataset_name
"""

    # Write .env file
    try:
        with open(env_file, "w") as f:
            f.write(env_content)
        print(f"✅ .env file created successfully!")
        return True
    except Exception as e:
        print(f"❌ Failed to create .env file: {e}")
        return False


def test_setup():
    """Test the environment setup"""
    print("\n🧪 Testing Setup...")
    print("=" * 20)

    # Load environment variables
    from dotenv import load_dotenv

    load_dotenv()

    issues = []

    # Test Google Cloud credentials
    try:
        from google.cloud import bigquery

        client = bigquery.Client()
        print(f"✅ BigQuery connection successful!")
        print(f"   Project ID: {client.project}")
    except Exception as e:
        print(f"❌ BigQuery connection failed: {e}")
        issues.append("BigQuery setup")

    # Test Gemini AI
    try:
        import google.generativeai as genai

        genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
        model = genai.GenerativeModel("gemini-1.5-pro")

        # Test with a simple prompt
        response = model.generate_content("Say 'Hello, setup successful!'")
        print(f"✅ Gemini AI connection successful!")
        print(f"   Test response: {response.text[:50]}...")
    except Exception as e:
        print(f"❌ Gemini AI connection failed: {e}")
        issues.append("Gemini AI setup")

    if not issues:
        print("\n🎉 All tests passed! Your setup is ready.")
        print("   Run: streamlit run app.py")
        return True
    else:
        print(f"\n⚠️  Issues found with: {', '.join(issues)}")
        print("   Check your .env file and credentials")
        return False


def create_directory_structure():
    """Create necessary directories"""
    print("\n📁 Creating directory structure...")

    directories = ["src", "tests"]

    for dir_name in directories:
        dir_path = Path(dir_name)
        dir_path.mkdir(exist_ok=True)
        print(f"✅ Created/verified: {dir_name}/")

    # Create __init__.py files
    for dir_name in directories:
        init_file = Path(dir_name) / "__init__.py"
        if not init_file.exists():
            init_file.touch()
            print(f"✅ Created: {init_file}")


def main():
    """Main setup function"""
    print("🤖 MultiAgentAI21 Setup Wizard")
    print("==============================")

    # Create directory structure
    create_directory_structure()

    # Check if .env already exists
    if Path(".env").exists():
        print("\n.env file already exists.")
        recreate = input("Recreate it? (y/n): ").strip().lower()
        if recreate != "y":
            print("Skipping .env creation...")
        else:
            if not create_env_file():
                return
    else:
        if not create_env_file():
            return

    # Test the setup
    test_setup()

    print("\n📋 Next steps:")
    print("1. Make sure all files are in place:")
    print("   - app.py")
    print("   - src/agent_core.py")
    print("   - requirements.txt")
    print("   - .env")
    print("2. Install dependencies: pip install -r requirements.txt")
    print("3. Run the app: streamlit run app.py")


if __name__ == "__main__":
    main()
